#!/usr/bin/env bash
#configures the server yo emsure its working properly.
#install nginx
##install net-tools if not installed
#sudo apt-get update
#sudo apt-get install -y net-tools

# Check if Nginx is running
if ! pgrep nginx > /dev/null ; then
  echo "Nginx is not running"
  exit 1
fi

# Check if Nginx is listening on port 80
if ! netstat -lnp | (grep -q :80 && grep -q nginx) ; then
  echo "Nginx is not listening on port 80"

  # Modify Nginx configuration to listen on port 80 for all active ipv4 ips
  sudo sed -i '/listen \[::\]:8080 default_server/ s/8080/80/' /etc/nginx/sites-enabled/default
  sudo sed -i '/listen 8080 default_server/ s/8080/80/' /etc/nginx/sites-available/default
  # Restart Nginx service
  sudo service nginx restart
fi
