#!/usr/bin/env bash
# Debugging to make nginx connect on port 80
sudo sed -i -e 's/listen \[::\]:8080 default_server/listen [::]:80 default_server/g' -e 's/listen 8080 default_server/listen 80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -f nginx
