#!/usr/bin/env bash
# Debugging to make nginx connect on port 80
sudo sed -i '/listen \[::\]:8080 default_server/ s/8080/80/' /etc/nginx/sites-enabled/default
sudo sed -i '/listen 8080 default_server/ s/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -f nginx
