#!/usr/bin/env bash
# Debugging to make nginx connect on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx stop
