#!/usr/bin/env bash
# This is a Bash script that displays the content of the file /etc/passwd.

#+ The script displays only:

#+    username
#+    user id
#+    Home directory path for the user


while IFS=: read -r f1 f2 f3 f4 f5 f6 f7; do
	echo "$f1:$f3:$f6"
done < /etc/passwd
