#!/usr/bin/env bash
# This is a Bash script that displays the content of the file /etc/passwd.

#+ The script displays only:

#+    username
#+    user id
#+    Home directory path for the user

FILE=/etc/passwd
while [[ "$FILE" ]]; do
	cat "$FILE" | cut -d : -f 1,3,6
	break
done
