#!/usr/bin/env bash
# This scripts gives information about the school file
#+ it checks if it exists nd is not emoty and also a regular file

file="$PWD/school"

if [[ -e "$file" ]]; then
	echo "school file exists"
	if [[ -s "$file" ]]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [[ -f "$file" ]]; then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
